config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :dashboard do
    get 'banks/index'
  end
  namespace :dashboard do
    get 'users/edit'
  end
  namespace :dashboard do
    resources :banks, expect: %i[destroy]
    resources :groups, expect: %i[destroy]
    resources :users, only: %i[edit update]
    resources :accounts, except: %i[destroy show]
    resources :financials, except: %i[destroy index] do
      post :change_paid
      collection do
        get :list_transction
      end
    end
  end
  root 'dashboard#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/financial.rb
# frozen_string_literal: true

class Financial < ApplicationRecord
  # Validates
  validates :transaction_type, :installments, presence: true
  before_save :set_total

  # Enumerates
  enum transaction_type: %i[credit debit]

  # Relationships
  belongs_to :account
  has_one :group, through: :account
  has_many :installments, dependent: :destroy
  accepts_nested_attributes_for :installments, reject_if: proc { |l|
                                                            l[:name].blank? ||
                                                              l[:payment_value].blank?
                                                          }, allow_destroy: true

  def total
    installments.collect(&:payment_value).sum
  end

  def set_total
    self[:total_transaction] = total
  end
end

app/controllers/dashboard/accounts_controller.rb
# frozen_string_literal: true

module Dashboard
  class AccountsController < DashboardController
    include MenuResources
    before_action :set_resources, only: %i[index]
    before_action :set_accounts, only: %i[edit update]
    before_action :find_groups, only: %i[new edit]
    before_action :find_banks, only: %i[new edit]

    def index
      @accounts = Account.where(group: current_user.groups).order(account: :asc)
    end

    def new
      @account = Account.new
    end

    def create
      @account = Account.new(accounts_params)
      if @account.save
        redirect_to dashboard_accounts_path, notice: 'Account successfully registered!'
      else
        alert_errors
      end
    end

    def edit; end

    def update
      if @account.update(accounts_params)
        redirect_to dashboard_accounts_path, notice: 'Account updated successfully!'
      else
        alert_errors
      end
    end

    def find_groups
      @groups = current_user.groups.where(status: 'active').order(name: :asc)
    end

    def find_banks
      @banks = current_user.banks.where(status: 'active').order(name: :asc)
    end

    private

    def alert_errors
      redirect_to dashboard_accounts_path, alert: @account.errors.full_messages.to_sentence
    end

    def set_accounts
      @account = Account.find(params[:id])
    end

    def accounts_params
      params.require(:account).permit(:agency, :account, :balance, :status, :account_type, :bank_id,
                                      :group_id)
    end
  end
end

app/controllers/dashboard/banks_controller.rb
# frozen_string_literal: true

module Dashboard
  class BanksController < DashboardController
    before_action :set_banks, only: %i[edit update]
    def index
      @banks = current_user.banks.order(name: :asc)
    end

    def new
      @bank = Bank.new
    end

    def create
      @bank = Bank.new(banks_params)
      @bank.user_id = current_user.id
      if @bank.save
        redirect_to dashboard_banks_path, notice: 'Bank was successfully created.'
      else
        alert_errors
      end
    end

    def edit; end

    def update
      if @bank.update(banks_params)
        redirect_to dashboard_banks_path, notice: 'Bank was successfully updated.'
      else
        alert_errors
      end
    end

    private

    def alert_errors
      redirect_to dashboard_banks_path, alert: @bank.errors.full_messages.to_sentence
    end

    def set_banks
      @bank = Bank.find(params[:id])
    end

    def banks_params
      params.require(:bank).permit(:name, :number, :status, :user_id)
    end
  end
end

app/controllers/dashboard/financials_controller.rb
# frozen_string_literal: true

module Dashboard
  class FinancialsController < DashboardController
    include MenuResources
    before_action :set_resources, only: %i[list_transction]
    before_action :set_financials, only: %i[edit update]
    before_action :find_accounts, only: %i[new edit]

    # def index
    #   @financials = Financial.where(account_id: current_user.accounts).order(created_at: :asc)
    # end

    def new
      @financial = Financial.new
    end

    def create
      @financial = Financial.new(financials_params)
      if @financial.save
        redirect_to url_default, notice: 'Transaction performed successfully!'
      else
        redirect_to url_default, alert: @financial.errors.full_messages.to_sentence
      end
    end

    def edit; end

    def update
      if @financial.update(financials_params)
        redirect_to url_default, notice: 'Transaction performed successfully!'
      else
        redirect_to url_default, alert: @financial.errors.full_messages.to_sentence
      end
    end

    def change_paid
      @installment = Installment.find(params[:financial_id])
      @installment.status = params[:status]
      @installment.payment_date = params[:payment_date]
      if @installment.save
        flash[:notice] = 'Payment made successfully!'
      else
        flash[:alert] = @installment.errors.full_messages.to_sentence
      end
    end

    def find_accounts
      @accounts = Account.where(group_id: params[:group])
    end

    def list_transction
      @transaction = Group.find_by(id: params[:group])
    end

    def url_default
      list_transction_dashboard_financials_path(group: params[:group])
    end

    private

    def set_financials
      @financial = Financial.find(params[:id])
    end

    def financials_params
      params.require(:financial).permit(:transaction_type, :account_id,
                                        installments_attributes: %i[name number payment_value payment_date due_date note status financial_id _destroy])
    end
  end
end

app/controllers/dashboard/groups_controller.rb
class Dashboard::GroupsController < DashboardController
  before_action :set_groups, only: %i[edit update]

  def index
    @groups = current_user.groups.order(name: :asc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(groups_params)
    @group.user_id = current_user.id

    if @group.save
      redirect_to dashboard_groups_path, notice: "#{@group.name} successfully registered!"
    else
      alert_errors
    end
  end

  def edit; end

  def update
    if @group.update(groups_params)
      redirect_to dashboard_groups_path, notice: "#{@group.name} updated successfully!"
    else
      alert_errors
    end
  end

  private

  def alert_errors
    redirect_to dashboard_groups_path, alert: @group.errors.full_messages.to_sentence
  end

  def set_groups
    @group = Group.find(params[:id])
  end

  def groups_params
    params.require(:group).permit(:name, :status, :user_id)
  end
end

app/controllers/dashboard/users_controller.rb
# frozen_string_literal: true

module Dashboard
  class UsersController < DashboardController
    include MenuResources
    before_action :set_resources, only: %i[edit]
    before_action :set_users, only: %i[edit update]
    before_action :allow_without_password, only: [:update]

    def edit
      return if params[:id] == current_user.id

      redirect_to root_path, alert: 'You are not allowed to edit another user'
    end

    def update
      if @user.update(users_params)
        redirect_to root_path, notice: "#{@user.first_name} successfully updated!"
      else
        alert_errors
      end
    end

    private

    def alert_errors
      redirect_to edit_dashboard_user_path(current_user), alert: @user.errors.full_messages.to_sentence
    end

    def set_users
      @user = User.find(params[:id])
    end

    def users_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :photo_profile)
    end

    # remove o input da validação do devise
    def allow_without_password
      return unless params[:user][:password].blank? && params[:user][:password_confirmation].blank?

      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  include MenuResources
  before_action :authenticate_user!
  before_action :set_resources, only: %i[index]
  layout 'dashboard'
  def index
    revenue
  end

  private

  def revenue
    user_id = current_user.id

    @revenue_paids = GetPaymentsSumServices.new(user_id, :revenue, :paid).call
    @revenue_unpaids = GetPaymentsSumServices.new(user_id, :revenue, :unpaid).call
    @expense_paids = GetPaymentsSumServices.new(user_id, :expense, :paid).call
    @expense_unpaids = GetPaymentsSumServices.new(user_id, :expense, :unpaid).call

    @groups = Group.where(user_id: current_user.id)
  end
end

app/helpers/dashboard/accounts_helper.rb
# frozen_string_literal: true

module Dashboard
  module AccountsHelper
  end
end

app/helpers/dashboard/banks_helper.rb
# frozen_string_literal: true

module Dashboard
  module BanksHelper
  end
end

app/helpers/dashboard/financials_helper.rb
# frozen_string_literal: true

module Dashboard
  module FinancialsHelper
  end
end

app/helpers/dashboard/groups_helper.rb
module Dashboard::GroupsHelper
end

app/helpers/dashboard/users_helper.rb
# frozen_string_literal: true

module Dashboard
  module UsersHelper
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/financials/_form.html.erb
<%= form_with model: [:dashboard, @financial] do |f| %>
  <%= hidden_field_tag "group", params[:group] %>
  <div class="p-4">
    <div class="form-row justify-content-lg-center">
      <%= hidden_field_tag :counter, 0 %>
      <%= hidden_field_tag :total_value, id:"sum" %>
      <div class="row">
        <div class="form-group col-md-6 col-lg-6">
          <% if Account.all.size > 0 %>
            <%= f.label :account_id %>
            <%= collection_select(:financial, :account_id, 
                                  @accounts, :id, :agency_with_account,  
                                  {prompt: 'Select'}, 
                                  class: "form-control") %>
          <% else %>
            <label> <%= f.label :bank_id %></label>
            <select class="form-control">
              <option>Select</option>
              <option>Register a Account</option>
            </select>
          <% end %>
        </div>
        <div class="form-group col-md-4 col-lg-4">
          <%= f.label :transaction_type %>
          <div class="form-check form-check-inline">
            <%=  f.collection_radio_buttons :transaction_type, Financial.transaction_types.map{ |a| [a.first,a.first] }, :first, :second  do |b| %>
              <div class="form-check form-check-inline">
                <%= b.radio_button class: "form-check-input" %>
                <%= b.label class: "form-check-label" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="form-group col-md-2 col-lg-2 text-center">
          <%= f.label :total_transaction %>
          <%= f.number_field :total_transaction, step: 0.01, class: "form-control", id:"sum", readonly: true %>
        </div>
      </div>
      <hr>
      <div class="row" id="installments">
        <%= f.fields_for :installments do |t| %>
          <%= render "installment_fields", f: t %>
        <% end %>
        <div class="mt-2 text-center" >
          <%= link_to_add_association "#{t ("buttons_default.add_transaction")}", f, :installments, class: "btn app-btn-primary w-50 theme-btn mx-auto" %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12 col-lg-10 offset-lg-1">
    <div class="px-4 mb-4 text-center">
      <%= f.submit class: 'btn app-btn-primary theme-btn my-1', data: { disable_with: 'Saving....⌛'} %>
    </div>
  </div>
<% end %>
<script>
  $(document).ready(function() {
      $('#installments')
        .on('cocoon:before-insert', function(e, add) {
          number = parseInt($('#counter').val()) + 1
          add.find("input[id*='number']").val(number);
          $('#counter').val(number);
        })
        .on("cocoon:before-remove", function(e, add) {
          number = parseInt($('#counter').val()) - 1
          add.find("input[id*='number']").val(number);
          $('#counter').val(number);
      })
      });
</script>

app/views/dashboard/financials/_installment_fields.html.erb
<div class="nested-fields">
  <div class="p-3">
    <div class="form-row justify-content-lg-center">
      <div class="row">
        <div class="form-group col-md-2 col-lg-4">
          <%= f.label :number %>
          <%= f.text_field :number, class: "form-control", readonly: true %>
        </div>
        <div class="form-group col-md-2 col-lg-4">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group col-md-2 col-lg-4">
          <%= f.label :payment_value %>
          <%= f.number_field :payment_value, step: 0.01, class: "form-control pay_value" %>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="form-group col-md-2 col-lg-4">
          <%= f.label :due_date %>
          <%= f.date_field :due_date, class: "form-control" %>
        </div>
        <div class="form-group col-md-2 col-lg-4">
          <%= f.label :payment_date %>
          <%= f.date_field :payment_date, class: "form-control" %>
        </div>
        <div class="form-group col-md-4 col-lg-4">
          <%= f.label :status %>
          <div class="form-check form-check-inline">
            <%=  f.collection_radio_buttons :status, Installment.statuses.map{ |a| [a.first,a.first] }, :first, :second  do |b| %>
              <div class="form-check form-check-inline">
                <%= b.radio_button class: "form-check-input" %>
                <%= b.label class: "form-check-label" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="form-group col-md-12 col-lg-12">
          <%= f.label :note %>
          <%= f.text_field :note, class: "form-control h-100" %>
        </div>
      </div>
    </div>
  </div>
  <div class="px-4 mb-4 text-center">
    <%= link_to_remove_association "#{t ("buttons_default.remove_transaction")}", f, class: "btn app-btn-danger w-25 theme-btn mx-auto" %>
  </div>
</div>
<script>

$(document).ready(function () {

  setInterval(function () { calculateSum() }, 500);
  input_value();
  calculateSum();

});

function calculateSum() {
  var sum = 0;
  $(".pay_value").each(
    function () {
      var vl = this.value.replace(',', '');
      if (!isNaN(vl) && vl.length != 0) {
        sum += parseFloat(vl);
      }
    });

  $("#sum").val(sum.toFixed(2));
}

function input_value() {
    $('input.pay_value').keyup(function (event) {
    if (event.which >= 37 && event.which <= 40) {
      event.preventDefault();
    }
    var $this = $(this);
    var num = $this.val().replace(/,/gi, "").split("").reverse().join("");
    var num2 = RemoveRougeChar(num.replace(/(.{9})/g, "$1,").split("").reverse().join(""));
    console.log(num2);
    $this.val(num2);
  });
}

function RemoveRougeChar(convertString) {
  if (convertString.substring(0, 1) == ",") {
    return convertString.substring(1, convertString.length)
  }
  return convertString;
}

</script>

app/views/dashboard/financials/_list_grid_paid.html.erb
      
<div class="table-responsive">
  <table id="paidTable" class="table table-hover text-center">
    <thead>
      <tr>
        <th scope="col"><%= t ("financial.account") %></th>
        <th scope="col"><%= t ("financial.due_date") %></th>
        <th scope="col"><%= t ("financial.payment_date") %></th>
        <th scope="col"><%= t ("financial.installment") %></th>
        <th scope="col"><%= t ("financial.transaction_type") %></th>
        <th scope="col"><%= t ("financial.total_transaction") %></th>
        <th scope="col"><%= t ("financial.action") %></th>
      </tr>
    </thead>
    <tbody>
      <% @transaction.financials.each do |financial| %>
        <% financial.installments.where(status: "paid").each do |installment| %>
          <tr>
            <td><%= financial&.account&.agency_with_account %></td>
            <td><%= l installment&.due_date %></td>
            <td><%= l installment&.payment_date %></td>
            <td><%= translate_attr(Financial, financial&.transaction_type) %></td>
            <td><%= installment&.number %> / <%= financial&.installments.size %></td>
            <td><%= financial.decorate.transact_format(currency_br(installment&.payment_value)) %></td>
            <td>
              <button type="button" class="btn btn-info text-white" data-bs-toggle="modal" data-bs-target="#show_<%= financial.id %>_Modal">
                <%= icon("eye") %> <%= t ("buttons_default.show") %>
              </button>
              <%= render 'show_receipt', financial: financial  %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/financials/_list_grid_unpaid.html.erb
<div class="table-responsive">
  <table id="unpaidTable" class="table table-hover text-center">
    <thead>
      <tr>
        <th scope="col"><%= t ("financial.account") %></th>
        <th scope="col"><%= t ("financial.due_date") %></th>
        <th scope="col"><%= t ("financial.installment") %></th>
        <th scope="col"><%= t ("financial.transaction_type") %></th>
        <th scope="col"><%= t ("financial.total_transaction") %></th>
        <th scope="col"><%= t ("financial.action") %></th>
      </tr>
    </thead>
    <tbody>
      <% @transaction.financials.each do |financial| %>
        <% financial.installments.where(status: "unpaid").each do |installment| %>
          <tr>
            <td><%= financial&.account&.agency_with_account %></td>
            <td><%= l installment&.due_date %></td>
            <td><%= translate_attr(Financial, financial&.transaction_type) %></td>
            <td><%= installment&.number %> / <%= financial&.installments.size %></td>
            <td><%= currency_br(installment&.payment_value) %></td>
            <td>
              <button type="button" class="btn app-btn-primary" data-bs-toggle="modal" data-bs-target="#pay_<%= installment.id %>_Modal">
                <%= icon("currency-dollar") %> <%= t ("buttons_default.pay") %>
              </button>
              <%= render 'pay_modal', installment: installment  %>
              <button type="button" class="btn btn-info text-white" data-bs-toggle="modal" data-bs-target="#show_<%= financial.id %>_Modal">
                <%= icon("eye") %> <%= t ("buttons_default.show") %>
              </button>
              <%= render 'show_receipt', financial: financial  %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/financials/_modal.html.erb
<div class="modal-header">
  <h5 class="modal-title mx-auto" id="ModalLabel">
    <%= action_name == "new" ? "New" : "Edit"%> Payment
  </h5>
</div>
<div class="modal-body">
  <%= render 'form', financial: @financial %>
</div>

app/views/dashboard/financials/_pay_modal.html.erb
<div class="modal fade" id="pay_<%= installment.id %>_Modal" tabindex="-1" aria-labelledby="pay_<%= installment.id %>_ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="pay_<%= installment.id %>_ModalLabel"><%= t ("financial.modal_title") %> <%= installment.name %></h5>
      </div>
      <%= form_with url: dashboard_financial_change_paid_path(installment.id), local: false, method: :post do %>
        <div class="modal-body">
          <div class="form-group">
            <%= hidden_field_tag "status", "paid" %>
            <%= label_tag :payment_date %>
            <%= date_field_tag :payment_date, params[:payment_date], class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t ("buttons_default.cancel") %></button>
          <%= button_tag(type: "submit", class: 'btn app-btn-primary theme-btn my-1', data: { disable_with: 'Saving....⌛'}) do %>
            <%= icon("check2-circle") %> <%= t ("buttons_default.confirm") %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/financials/_show_receipt.html.erb
<div class="modal fade" id="show_<%= financial.id %>_Modal" tabindex="-1" aria-labelledby="show_<%= financial.id %>_ModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="show_<%= financial.id %>_ModalLabel"><%= t ("financial.receipt_list") %></h5>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
          <table id="showTable" class="table table-hover text-center">
            <thead>
              <tr>
                <th scope="col"><%= t ("financial.due_date") %></th>
                <th scope="col"><%= t ("financial.payment_date") %></th>
                <th scope="col"><%= t ("financial.installment") %></th>
                <th scope="col"><%= t ("financial.transaction_type") %></th>
                <th scope="col"><%= t ("financial.status") %></th>
                <th scope="col"><%= t ("financial.total_transaction") %></th>
              </tr>
            </thead>
            <tbody>
              <%  financial.installments.each do |installment| %>
                <tr>
                  <td><%= l installment&.due_date %></td>
                  <td><%= l installment&.payment_date if installment&.payment_date.present? %></td>
                  <td><%= translate_attr(Financial, financial&.transaction_type) %></td>
                  <td><%= installment&.number %> / <%= financial&.installments.size %></td>
                  <td><%= installment.decorate.status_format(installment&.status) %></td>
                  <td><%= financial.decorate.transact_format(currency_br(installment&.payment_value)) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t ("buttons_default.cancel") %></button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/financials/change_paid.js.erb
window.location.reload();

app/views/dashboard/financials/edit.js.erb
$("#modal").find(".modal-content").html("<%= j render 'modal', locals: { financial: @financial } %>");
$("#modal").modal();

app/views/dashboard/financials/index.html.erb
<h1>Dashboard::Financials#index</h1>
<p>Find me in app/views/dashboard/financials/index.html.erb</p>

app/views/dashboard/financials/list_transction.html.erb
<h1 class="app-page-title"><%= t ("financial.title_financial") %></h1>
<hr class="mb-4">
<div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
  <div class="d-grid gap-2 d-md-flex justify-content-md-end pb-2">
    <%= link_to new_dashboard_financial_path(group: params[:group]), remote: true, class:"btn app-btn-primary theme-btn me-md-2", data: {bs_toggle:"modal", bs_target:"#modal"} do %>
      <%= icon("plus-square") %> <%= t ("buttons_default.add") %>
    <% end %>
  </div>
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-paid-tab" data-bs-toggle="tab" data-bs-target="#nav-paid" type="button" role="tab" aria-controls="nav-paid" aria-selected="true"><%= t ("buttons_default.paid") %></button>
      <button class="nav-link" id="nav-unpaid-tab" data-bs-toggle="tab" data-bs-target="#nav-unpaid" type="button" role="tab" aria-controls="nav-unpaid" aria-selected="false"><%= t ("buttons_default.unpaid") %></button>
    </div>
  </nav>
  <div class="app-card app-card-orders-table shadow-sm mb-5">
    <div class="app-card-body">
          <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-paid" role="tabpanel" aria-labelledby="nav-paid-tab">
        <%= render 'list_grid_paid' %>
        </div>
        <div class="tab-pane fade" id="nav-unpaid" role="tabpanel" aria-labelledby="nav-unpaid-tab">
        <%= render 'list_grid_unpaid' %>
        </div>
      </div>
      <!--//table-responsive-->
    </div>
    <!--//app-card-body-->
  </div>
  <!--//app-card-->
</div>
<!--//tab-pane-->

app/views/dashboard/financials/new.js.erb
$("#modal").find(".modal-content").html("<%= j render 'modal', locals: { financial: @financial } %>");
$("#modal").modal();