config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :dashboard do
    get 'banks/index'
  end
  namespace :dashboard do
    get 'users/edit'
  end
  namespace :dashboard do
    resources :banks, expect: %i[destroy]
    resources :groups, expect: %i[destroy]
    resources :users, only: %i[edit update]
    resources :accounts, except: %i[destroy show]
    resources :financials, except: %i[destroy index] do
      post :change_paid
      collection do
        get :list_transction
      end
    end
  end
  root 'dashboard#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  # Validates
  validates :name, :status, presence: true
  validates :name, uniqueness: { scope: :user, case_sensitive: false }

  # Enumerates
  enum status: %i[active inactive]

  # Relationships
  belongs_to :user
  has_many :accounts, dependent: :destroy
  has_many :financials, through: :accounts

  def active?
    status == 'active'
  end
end

app/controllers/dashboard/accounts_controller.rb
# frozen_string_literal: true

module Dashboard
  class AccountsController < DashboardController
    include MenuResources
    before_action :set_resources, only: %i[index]
    before_action :set_accounts, only: %i[edit update]
    before_action :find_groups, only: %i[new edit]
    before_action :find_banks, only: %i[new edit]

    def index
      @accounts = Account.where(group: current_user.groups).order(account: :asc)
    end

    def new
      @account = Account.new
    end

    def create
      @account = Account.new(accounts_params)
      if @account.save
        redirect_to dashboard_accounts_path, notice: 'Account successfully registered!'
      else
        alert_errors
      end
    end

    def edit; end

    def update
      if @account.update(accounts_params)
        redirect_to dashboard_accounts_path, notice: 'Account updated successfully!'
      else
        alert_errors
      end
    end

    def find_groups
      @groups = current_user.groups.where(status: 'active').order(name: :asc)
    end

    def find_banks
      @banks = current_user.banks.where(status: 'active').order(name: :asc)
    end

    private

    def alert_errors
      redirect_to dashboard_accounts_path, alert: @account.errors.full_messages.to_sentence
    end

    def set_accounts
      @account = Account.find(params[:id])
    end

    def accounts_params
      params.require(:account).permit(:agency, :account, :balance, :status, :account_type, :bank_id,
                                      :group_id)
    end
  end
end

app/controllers/dashboard/banks_controller.rb
# frozen_string_literal: true

module Dashboard
  class BanksController < DashboardController
    before_action :set_banks, only: %i[edit update]
    def index
      @banks = current_user.banks.order(name: :asc)
    end

    def new
      @bank = Bank.new
    end

    def create
      @bank = Bank.new(banks_params)
      @bank.user_id = current_user.id
      if @bank.save
        redirect_to dashboard_banks_path, notice: 'Bank was successfully created.'
      else
        alert_errors
      end
    end

    def edit; end

    def update
      if @bank.update(banks_params)
        redirect_to dashboard_banks_path, notice: 'Bank was successfully updated.'
      else
        alert_errors
      end
    end

    private

    def alert_errors
      redirect_to dashboard_banks_path, alert: @bank.errors.full_messages.to_sentence
    end

    def set_banks
      @bank = Bank.find(params[:id])
    end

    def banks_params
      params.require(:bank).permit(:name, :number, :status, :user_id)
    end
  end
end

app/controllers/dashboard/financials_controller.rb
# frozen_string_literal: true

module Dashboard
  class FinancialsController < DashboardController
    include MenuResources
    before_action :set_resources, only: %i[list_transction]
    before_action :set_financials, only: %i[edit update]
    before_action :find_accounts, only: %i[new edit]

    # def index
    #   @financials = Financial.where(account_id: current_user.accounts).order(created_at: :asc)
    # end

    def new
      @financial = Financial.new
    end

    def create
      @financial = Financial.new(financials_params)
      if @financial.save
        redirect_to url_default, notice: 'Transaction performed successfully!'
      else
        redirect_to url_default, alert: @financial.errors.full_messages.to_sentence
      end
    end

    def edit; end

    def update
      if @financial.update(financials_params)
        redirect_to url_default, notice: 'Transaction performed successfully!'
      else
        redirect_to url_default, alert: @financial.errors.full_messages.to_sentence
      end
    end

    def change_paid
      @installment = Installment.find(params[:financial_id])
      @installment.status = params[:status]
      @installment.payment_date = params[:payment_date]
      if @installment.save
        flash[:notice] = 'Payment made successfully!'
      else
        flash[:alert] = @installment.errors.full_messages.to_sentence
      end
    end

    def find_accounts
      @accounts = Account.where(group_id: params[:group])
    end

    def list_transction
      @transaction = Group.find_by(id: params[:group])
    end

    def url_default
      list_transction_dashboard_financials_path(group: params[:group])
    end

    private

    def set_financials
      @financial = Financial.find(params[:id])
    end

    def financials_params
      params.require(:financial).permit(:transaction_type, :account_id,
                                        installments_attributes: %i[name number payment_value payment_date due_date note status financial_id _destroy])
    end
  end
end

app/controllers/dashboard/groups_controller.rb
class Dashboard::GroupsController < DashboardController
  before_action :set_groups, only: %i[edit update]

  def index
    @groups = current_user.groups.order(name: :asc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(groups_params)
    @group.user_id = current_user.id

    if @group.save
      redirect_to dashboard_groups_path, notice: "#{@group.name} successfully registered!"
    else
      alert_errors
    end
  end

  def edit; end

  def update
    if @group.update(groups_params)
      redirect_to dashboard_groups_path, notice: "#{@group.name} updated successfully!"
    else
      alert_errors
    end
  end

  private

  def alert_errors
    redirect_to dashboard_groups_path, alert: @group.errors.full_messages.to_sentence
  end

  def set_groups
    @group = Group.find(params[:id])
  end

  def groups_params
    params.require(:group).permit(:name, :status, :user_id)
  end
end

app/controllers/dashboard/users_controller.rb
# frozen_string_literal: true

module Dashboard
  class UsersController < DashboardController
    include MenuResources
    before_action :set_resources, only: %i[edit]
    before_action :set_users, only: %i[edit update]
    before_action :allow_without_password, only: [:update]

    def edit
      return if params[:id] == current_user.id

      redirect_to root_path, alert: 'You are not allowed to edit another user'
    end

    def update
      if @user.update(users_params)
        redirect_to root_path, notice: "#{@user.first_name} successfully updated!"
      else
        alert_errors
      end
    end

    private

    def alert_errors
      redirect_to edit_dashboard_user_path(current_user), alert: @user.errors.full_messages.to_sentence
    end

    def set_users
      @user = User.find(params[:id])
    end

    def users_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :photo_profile)
    end

    # remove o input da validação do devise
    def allow_without_password
      return unless params[:user][:password].blank? && params[:user][:password_confirmation].blank?

      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  include MenuResources
  before_action :authenticate_user!
  before_action :set_resources, only: %i[index]
  layout 'dashboard'
  def index
    revenue
  end

  private

  def revenue
    user_id = current_user.id

    @revenue_paids = GetPaymentsSumServices.new(user_id, :revenue, :paid).call
    @revenue_unpaids = GetPaymentsSumServices.new(user_id, :revenue, :unpaid).call
    @expense_paids = GetPaymentsSumServices.new(user_id, :expense, :paid).call
    @expense_unpaids = GetPaymentsSumServices.new(user_id, :expense, :unpaid).call

    @groups = Group.where(user_id: current_user.id)
  end
end

app/helpers/dashboard/accounts_helper.rb
# frozen_string_literal: true

module Dashboard
  module AccountsHelper
  end
end

app/helpers/dashboard/banks_helper.rb
# frozen_string_literal: true

module Dashboard
  module BanksHelper
  end
end

app/helpers/dashboard/financials_helper.rb
# frozen_string_literal: true

module Dashboard
  module FinancialsHelper
  end
end

app/helpers/dashboard/groups_helper.rb
module Dashboard::GroupsHelper
end

app/helpers/dashboard/users_helper.rb
# frozen_string_literal: true

module Dashboard
  module UsersHelper
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/groups/_form.html.erb
<%= form_with model: [:dashboard, @group] do |f| %>
  <div class="p-4">
    <div class="form-row justify-content-lg-center">
      <div class="form-group col-md-12 col-lg-12">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group col-md-12 col-lg-12 mt-3 text-center">
        <div class="status-label"><%= f.label :status, class: "form-check-label" %></div>
        <div class="status-label">
          <%=  f.collection_radio_buttons :status, Group.statuses.map{ |a| [a.first,a.first] }, :first, :second  do |b| %>
            <div class="form-check form-check-inline">
              <%= b.radio_button class: "form-check-input" %>
              <%= b.label class: "form-check-label" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12 col-lg-10 offset-lg-1">
    <div class="px-4 mb-4 text-center">
      <%= f.submit class: 'btn app-btn-primary theme-btn my-1', data: { disable_with: 'Saving....⌛'} %>
      <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><%= t ("buttons_default.cancel") %></button>
    </div>
  </div>
<% end %>

app/views/dashboard/groups/_modal.html.erb
<div class="modal-header">
  <h5 class="modal-title mx-auto" id="ModalLabel">
    <%= action_name == "new" ? "New" : "Edit"%> Group
  </h5>
</div>
<div class="modal-body">
  <%= render 'form', group: @group %>
</div>

app/views/dashboard/groups/edit.js.erb
$("#modal").find(".modal-content").html("<%= j render 'modal', locals: { group: @group } %>");
$("#modal").modal();

app/views/dashboard/groups/index.html.erb
<h1 class="app-page-title"><%= t ("group.title_group") %></h1>
<hr class="mb-4">
<div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
  <div class="d-grid gap-2 d-md-flex justify-content-md-end pb-2">
    <%= link_to new_dashboard_group_path, remote: true, class:"btn app-btn-primary theme-btn me-md-2", data: {bs_toggle:"modal", bs_target:"#modal"} do %>
      <%= icon("plus-square") %> <%= t ("buttons_default.add") %>
    <% end %>
  </div>
  <div class="app-card app-card-orders-table shadow-sm mb-5">
    <div class="app-card-body">
      <div class="table-responsive">
        <table class="table app-table-hover mb-0 text-center">
          <thead>
            <tr>
              <th class="cell"><%= t ("group.name") %></th>
              <th class="cell"><%= t ("group.status") %></th>
              <th class="cell"><%= t ("group.action") %></th>
            </tr>
          </thead>
          <tbody>
            <% @groups.each do |group| %>
              <tr>
                <td class="cell"><%= group&.name %></td>
                <td class="cell"><%= group&.active? ? '✅' : '❌' %></td>
                <td class="cell">
                  <%= link_to edit_dashboard_group_path(group), remote: true, class:"btn app-btn-primary theme-btn mx-auto", data: {bs_toggle:"modal", bs_target:"#modal"} do %>
                    <%= icon("pencil-square") %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!--//table-responsive-->
    </div>
    <!--//app-card-body-->
  </div>
  <!--//app-card-->
</div>
<!--//tab-pane-->

app/views/dashboard/groups/new.js.erb
$("#modal").find(".modal-content").html("<%= j render 'modal', locals: { group: @group } %>");
$("#modal").modal();